config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  # devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # devise_scope :user do
  # delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  mount ActionCable.server => "/cable"
  root to: 'users#index'
  resources :criterias
  resources :answers, only:[:create, :show] do
    resources :conversations, only: :create
  end
  resources :conversations, only: [:show, :index] do
    resources :messages, only: :create
  end
  delete '/logout' => 'registrations#destroy'
  get '/profile' => 'pages#profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/criterias_controller.rb
class CriteriasController < ApplicationController

   def edit
    @user = User.find(params[:id])
   end

   def update
    @user = User.find(params[:id])
      if @user.update(user_params)
      redirect_to root_path
    else
      @user.errors.full_messages
      render :edit
   end
 end

   private

   def user_params
    params.require(:user).permit(:opponent_ranking, :opponent_gender, :search_radius)
   end
end

app/views/criterias/edit.html.erb
<div class="container">
 <p class="page-title">Your criterias</p>
   <div class="card-form">
     <div class="card-criteria">
        <%= simple_form_for @user, url: criteria_path(@user), method: :patch do |f| %>
        <%= f.input :opponent_ranking, collection: [["1 - Novice", 1],["2 - Beginner", 2], ["3 - Intermediate", 3], ["4 - Advanced", 4], ["5 - Expert", 5]], hint: "If you select 3, we will show you players level 2-3-4" %>
        <%= f.input :opponent_gender, as: :select, collection: ["male", "female", "both"] %>
        <%= f.input :search_radius, hint: "Choose your radius from 0 to 50km" %>
        <%= f.button :submit, "Update", class: "btn btn-success" %>
      <% end %>
      </div>
    </div>
  </div>