config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  # devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # devise_scope :user do
  # delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  mount ActionCable.server => "/cable"
  root to: 'users#index'
  resources :criterias
  resources :answers, only:[:create, :show] do
    resources :conversations, only: :create
  end
  resources :conversations, only: [:show, :index] do
    resources :messages, only: :create
  end
  delete '/logout' => 'registrations#destroy'
  get '/profile' => 'pages#profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :picture, PictureUploader

  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  DEFAULTS = {
    search_radius: 50,
    opponent_gender: ["male", "female"],
    name: "No Name",
    address: "",
    gender: "male",
    ranking: 2,
    age: "",
    picture: "../../assets/images/default.jpg"
  }.freeze

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many :conversation_users
  has_many :conversations, through: :conversation_users
  has_many :answers
  has_many :receiver_answers, foreign_key: "receiver_id", class_name: 'Answer'

  scope :all_except_me, ->(user) { where.not(id: user) }
  scope :opponent_with_gender, ->(opponent_gender) { opponent_gender == 'both' ? all : where(gender: opponent_gender || DEFAULTS[:opponent_gender]) }
  scope :has_answer, ->(user) { joins(:answers).where(answers: { user: user})}
  scope :has_feedback_by, ->(user) {joins(:receiver_answers).merge(Answer.where(user: user))}
  scope :has_no_feedback_by, ->(user) {where.not(id: has_feedback_by(user))}
  scope :opponent_with_ranking, ->(opponent_ranking) { where(ranking: ((opponent_ranking - 1)..(opponent_ranking + 1))) }
  scope :interlocutors, -> (conversation, current_user) {
    joins(:conversation_users)
    .where(conversation_users: {conversation_id: conversation.id})
    .all_except_me(current_user)
  }

  scope :displayable_for, ->(user) {
    all_except_me(user)
      .has_no_feedback_by(user)
      .near(user.address, user.safe_search_radius)
      #.opponent_with_ranking(user.opponent_ranking || DEFAULTS[:ranking])
      #.opponent_with_gender(user.opponent_gender)
    }

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  def already_liked?(user)
    user.receiver_answers.like.exists?(user: self)
  end

  def safe_search_radius
    search_radius  || DEFAULTS[:search_radius]
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  def destroy
    registration[:user_id] = nil
    redirect_to root_path
  end


  def update
    if current_user.update(user_params)
      flash[:success] = 'Your profile has been updated.'
      redirect_to profile_path
    else
      flash[:error] = current_user.errors.full_messages
      render :edit
   end
  end


  private

  def user_params
    params.require(:user).permit(:name, :ranking, :gender, :age, :address, :picture, :hand, :description, :club)
  end

  def after_sign_up_path_for(resource)
    edit_user_registration_path
  end
  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.displayable_for(current_user)
    @answer = Answer.new
  end
end

app/views/users/index.html.erb
<div class="cards-container" >
  <div id="viewport">
    <div class="page-adjust-criterias">
      <p class="page-title">More Tennis Partners?</p>
      <%= link_to "Adjust your Search Criterias", edit_criteria_path(current_user), class: "btn btn-success" %>
    </div>


    <ul class="stack">
      <% @users.each do |user|%>
        <li data-index="<%= user.id %>">
          <div class="card-picture" style="background-image: url(<%= cl_image_path user.picture unless user.picture.blank?%>);">
            <div class="card-name-age"> <%= user.name %>, <%= user.age %>
            </div>
          </div>

          <div class="card-info" >
            <div class="icons-card" >
              <div>
                <i class="fas fa-map-marker-alt"></i>
               at <%= Geocoder::Calculations.distance_between([current_user.latitude,current_user.longitude], [user.latitude,user.longitude]).round(1) %> km
                </div>
              <div>
                <i class="fas fa-caret-right" ></i>
                <%= user.hand %>
              </div>
            </div>

            <div class="background-shadow">
              <i class="fas fa-home"></i>
              <%= user.club %>
            </div>

            <div class="card-rank">
              <i class="fas fa-trophy"></i>
              Ranking: <%= user.ranking %>
            </div>

            <div class="background-shadow">
              <h6 class="card-description" >
                <i class="fas fa-info"></i>
                <%= user.description %>
              </h6>
            </div>
          </div>

          <%= simple_form_for @answer do |f| %>
            <div class="bottom-buttons">
              <%= f.hidden_field :receiver_id, :value => user.id %>
              <%= f.button :button, "No Way!", type: :submit, name: "answer[status]", value: "dislike", class: "btn btn-danger", id: "dislike-#{user.id}" %>
              <%= f.button :button, "Let's go!", type: :submit, name: "answer[status]", value: "like", class: "btn btn-success", id: "like-#{user.id}" %>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>