config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  # devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # devise_scope :user do
  # delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  mount ActionCable.server => "/cable"
  root to: 'users#index'
  resources :criterias
  resources :answers, only:[:create, :show] do
    resources :conversations, only: :create
  end
  resources :conversations, only: [:show, :index] do
    resources :messages, only: :create
  end
  delete '/logout' => 'registrations#destroy'
  get '/profile' => 'pages#profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
  enum status: [:like, :dislike, :match]
  validates :status, presence: true
  validates :user, uniqueness: { scope: :receiver }

  scope :involving, ->(receiver, user) { where(user: receiver).where(receiver: user) }
  scope :likes_between, ->(receiver, user) { involving(receiver, user).like }

  before_create :check_for_match

  private

  def check_for_match
    # On sort de la method si le receveur n'a pas deja liké le user
    return unless receiver.already_liked?(user)
    # On set le status de l'answer en cours de creation a match
    self.status = :match
    # On update le like du receveur pour devenir à son tour un match
    self.class.likes_between(receiver, user).each &:match!
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @answer = current_user.answers.new(answer_params)
    if @answer.save
      return redirect_to answer_path(@answer) if @answer.match?
      redirect_to root_path
    else
      flash[:notice] = 'Impossible to like/dislike, try again'
      redirect_to root_path
    end
  end


  def show
    @answer = Answer.match.find(params[:id])
  end


  private

  def answer_params
    params.require(:answer).permit(:status, :user_id, :receiver_id)
  end
end

app/views/answers/show.html.erb
<div class="container">
  <p class="page-title">It's a match!</p>
  <div class="logo-tn">
    <%= cl_image_tag("TN_icone.png") %>
  </div>


    <div class="cards">
      <div class="card-match">
        <div class="profile-picture" style="background-image: url(<%= cl_image_path current_user.picture %>);">
        </div>
        <p class="name-font"><%= current_user.name %></p>
      </div>


      <div class="card-match">
        <div class="profile-picture" style="background-image: url(<%= cl_image_path @answer.receiver.picture %>);">
        </div>
        <p class="name-font"><%= @answer.receiver.name %></p>
      </div>
    </div>
  </div>

    <div class="button-match">
      <%= link_to "Keep swiping", root_path, class: "btn btn-warning" %>
      <%= link_to "Message your new bro!", answer_conversations_path(@answer), method: :post, class: "btn btn-warning" %>
    </div>
</div>